alter session set "_oracle_script"=true;
DROP USER HANDSOME CASCADE;

CREATE USER handsome IDENTIFIED BY handsome
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA 10m ON users
    QUOTA 10m ON apps;

GRANT
    CREATE SESSION,
    CREATE TABLE,
    CREATE PROCEDURE,
    CREATE TRIGGER,
    CREATE VIEW,
    CREATE SEQUENCE,
    CREATE TYPE
TO handsome;
